/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MadeToOrderRouteImport } from './routes/made-to-order'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiCarSearchRouteImport } from './routes/api/ai-car-search'

const MadeToOrderRoute = MadeToOrderRouteImport.update({
  id: '/made-to-order',
  path: '/made-to-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCarSearchRoute = ApiAiCarSearchRouteImport.update({
  id: '/api/ai-car-search',
  path: '/api/ai-car-search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/made-to-order': typeof MadeToOrderRoute
  '/api/ai-car-search': typeof ApiAiCarSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/made-to-order': typeof MadeToOrderRoute
  '/api/ai-car-search': typeof ApiAiCarSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/made-to-order': typeof MadeToOrderRoute
  '/api/ai-car-search': typeof ApiAiCarSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/auth' | '/made-to-order' | '/api/ai-car-search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/auth' | '/made-to-order' | '/api/ai-car-search'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/made-to-order'
    | '/api/ai-car-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  MadeToOrderRoute: typeof MadeToOrderRoute
  ApiAiCarSearchRoute: typeof ApiAiCarSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/made-to-order': {
      id: '/made-to-order'
      path: '/made-to-order'
      fullPath: '/made-to-order'
      preLoaderRoute: typeof MadeToOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-car-search': {
      id: '/api/ai-car-search'
      path: '/api/ai-car-search'
      fullPath: '/api/ai-car-search'
      preLoaderRoute: typeof ApiAiCarSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  MadeToOrderRoute: MadeToOrderRoute,
  ApiAiCarSearchRoute: ApiAiCarSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
